### ISSUE TITLE
Text field appearance

### ISSUE THREAD

**Issue by ddonahue99** [yob/prawn-forms#1]
Is there any way to change the appearance of the default text? For example, something like:

```
pdf.font_size(16) do
  pdf.text_field "name", x, y, w, h, :default => "should be big"
end
```

Does not appear to have any effect. I also tried changing the height of the field but that didn't do much but shift the positioning.

Any ideas?

Thanks,
Dave

**Comment by yob** [comment]
prawn-forms was mostly an experiment and the API is pretty minimal, so I don't think it has what you're after.

I'll accept patches if you can work it out.

**Comment by ddonahue99** [comment]
I figured that would be the case, just making sure I hadn't missed any obvious details. Thanks for the quick response.
